In [4]:
import pandas as pd
import os
import numpy as np
from datetime import datetime
from zoneinfo import ZoneInfo
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
pd.set_option('display.max_columns', None)

In [45]:
df_desgravamen= pd.read_excel('C:/DATOS/TRAMAS DE ERRORES PRESTAMOS - Enero- Junio26 - muestra.xlsx', sheet_name=0, 
                              dtype={'DESCRIPCION ERROR': str, 'CÓD. CERTIFICADO CANAL': str, 'CÓDIGO ERROR': str })
df_desgravamen.columns = (df_desgravamen.columns.str.strip().str.upper()
                            .str.replace(r'[^A-Za-z0-9]', '_', regex=True))

In [46]:
df_desgravamen= df_desgravamen[['C_D__CERTIFICADO_CANAL','TIPO_MOVIMIENTO','C_DIGO_ERROR', 'DESCRIPCI_N_ERROR',
                                'MONEDA','PRIMABRUTACAN','FEC__INICIO','FEC__FIN']]

In [47]:
df_desgravamen= df_desgravamen.rename(columns={'C_D__CERTIFICADO_CANAL':'CODIGO_CERTIFICADO',
                                               'C_DIGO_ERROR':'CODIGO_ERROR', 'DESCRIPCI_N_ERROR':'DESCRIPCION_ERROR',                                            
                                                'FEC__INICIO':'FECHA_INICIO', 'FEC__FIN':'FECHA_FIN', 
                                                'PRIMABRUTACAN':'PRIMA_BRUTA'})

In [48]:

filtro = df_desgravamen['CODIGO_CERTIFICADO'].str.startswith('C', na=False)
df_desgravamen.loc[filtro, 'CODIGO_CERTIFICADO'] = (df_desgravamen.loc[filtro, 'CODIGO_CERTIFICADO'].str[1:])
df_desgravamen['FECHA_INICIO']= pd.to_datetime(df_desgravamen['FECHA_INICIO'], errors='coerce').dt.date
df_desgravamen['FECHA_FIN']= pd.to_datetime(df_desgravamen['FECHA_FIN'], errors='coerce').dt.date
df_desgravamen['CODIGO_ERROR'] = df_desgravamen['CODIGO_ERROR'].apply(lambda x: str(x).zfill(4) if pd.notnull(x) else "")

In [49]:
df_desgravamen.head(3)

,CODIGO_CERTIFICADO,TIPO_MOVIMIENTO,CODIGO_ERROR,DESCRIPCION_ERROR,MONEDA,PRIMA_BRUTA,FECHA_INICIO,FECHA_FIN
0,00110002304000136030,Renovacion,7578,LA FECHA DE INICIO DE VIGENCIA DEL PAGO ES DI...,SOL,61.44,2023-08-01,2023-09-01
1,00110002304000136030,Renovacion,0199,No se puede ejecutar la validación VAL – Prima...,SOL,61.44,2023-08-01,2023-09-01
2,00110002304000136030,Renovacion,0199,No se puede ejecutar la validación Valida la t...,SOL,61.44,2023-08-01,2023-09-01

In [49]:
df_desgravamen= pd.read_csv("C:/datos/reporte errores tc.csv", encoding='latin1', sep=';',dtype={'CERTIFICADO': str, 
                                                                                                       'CODIGO_ERROR': str})

C:\Users\xt11442\AppData\Local\Temp\ipykernel_26832\2786429416.py:1: DtypeWarning: Columns (0: TIPO_MOVIMIENTO, 1: ORIGEN_ERROR, 2: DESCRIPCION_ERROR, 3: OBSERVACION, 4: MONEDA) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desgravamen= pd.read_csv("C:/datos/reporte errores tc.csv", encoding='latin1', sep=';',dtype={'CERTIFICADO': str,

In [52]:
df_desgravamen['CERTIFICADO'] = df_desgravamen["CERTIFICADO"].str[1:]

In [42]:
df_desgravamen['CODIGO_ERROR'] = df_desgravamen['CODIGO_ERROR'].apply(lambda x: str(x).zfill(4) if pd.notnull(x) else "")

In [28]:
df_desgravamen.head(3)

,CODIGO_CERTIFICADO,TIPO_MOVIMIENTO,CODIGO_ERROR,DESCRIPCION_ERROR,MONEDA,PRIMA_BRUTA,FECHA_INICIO,FECHA_FIN
0,00110128604000821855,Renovacion,0199,"No se puede ejecutar la validación Val, Valida...",SOL,24.45,2025-07-15,2025-08-15
1,00110128604000821855,Renovacion,0199,No se puede ejecutar la validación Valida la t...,SOL,24.45,2025-07-15,2025-08-15
2,00110128604000821855,Renovacion,0199,No se puede ejecutar la validación Val-Prima b...,SOL,24.45,2025-07-15,2025-08-15

In [34]:
df_desgravamen['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
0199    202
7578     80
1150     38
Name: count, dtype: int64

In [30]:

df_desgravamen.to_csv(
    "C:/datos/reporte_errores_prestamos_utf8.csv",
    encoding="utf-8", index=False)

In [ ]:
schema_desgravamen = [
        bigquery.SchemaField("CERTIFICADO", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("TIPO_MOVIMIENTO", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("ORIGEN_ERROR", bigquery.enums.SqlTypeNames.DATE),
        bigquery.SchemaField("CODIGO_ERROR", bigquery.enums.SqlTypeNames.INTEGER),
        bigquery.SchemaField("DESCRIPCION_ERROR", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("OBSERVACION", bigquery.enums.SqlTypeNames.INTEGER),
        bigquery.SchemaField("MONEDA", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("PRIMA_BRUTA", bigquery.enums.SqlTypeNames.FLOAT),
        
        ]

In [50]:
df_desgravamen.info()

<class 'pandas.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CODIGO_CERTIFICADO  329 non-null    str
 1   TIPO_MOVIMIENTO     329 non-null    str
 2   CODIGO_ERROR        329 non-null    str
 3   DESCRIPCION_ERROR   329 non-null    str
 4   MONEDA              329 non-null    str
 5   PRIMA_BRUTA         329 non-null    float64
 6   FECHA_INICIO        317 non-null    object
 7   FECHA_FIN           317 non-null    object
dtypes: float64(1), object(2), str(5)
memory usage: 20.7+ KB